stages:
- name: Build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: reti/myapp
      registry: 127.0.0.1:34891
timeout: 60
notification: {}
